# **<span style='color:lightblue;'>Pandas</span>**

Pandas is a fundamental, open-source Python library used for **data analysis and manipulation**. It provides powerful and flexible data structures designed to make working with labeled, relational data (like spreadsheets or SQL tables) both easy and intuitive.


## **Two Things**
1. **Series:** 1-Dimensional Data (Single Column)
2. **DataFrame:** 2-Dimensional Data (Table with Rows & Columns)

**Installation:**

```bash
pip install pandas
```

**Usage:**

```python
import pandas as pd
```

> The pandas library works fabulously with **numpy**.

## **Series**

1. Is Indexed
2. Is Ordered
3. Can store mixed types (but is not prefered)

In [9]:
li = [1, 2, 3]

In [10]:
import numpy as np

a = np.array(li)
print(a, type(a), sep='\n')

[1 2 3]
<class 'numpy.ndarray'>

In [11]:
import pandas as pd

a = pd.Series(li)
print(a, type(a), sep='\n')

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>

### **Custom Index**

In [87]:
b = pd.Series(li, index=['a', 1, 44.5])
print(b)

a       1
1       2
44.5    3
dtype: int64

### **Dictionary in Series**

In [93]:
country = {'Nepal': 'Bandu', 'India': 'Shyam', 'USA': 'Henry'}

In [94]:
import pandas as pd

country_series = pd.Series(country)

print(country_series)

Nepal    Bandu
India    Shyam
USA      Henry
dtype: object

In [95]:
import pandas as pd

only_nepal = pd.Series(country, index=['Nepal'])
print(only_nepal)

Nepal    Bandu
dtype: object

### **Populating Random Data**

In [107]:
import pandas as pd
import numpy as np

series = pd.Series(np.random.randint(low=1, high=6, size=5))
print(series)

0    3
1    5
2    1
3    2
4    1
dtype: int64

## **Stuffs...**

In [109]:
import pandas as pd

series = pd.Series(['Bandu', 'Bhidu', 'Bob', 'Banku'])
print(series)

0    Bandu
1    Bhidu
2      Bob
3    Banku
dtype: object

In [114]:
print(series[0])

Bandu

In [115]:
print(series.head(2))

0    Bandu
1    Bhidu
dtype: object

In [122]:
print(series.tail(2))

2      Bob
3    Banku
dtype: object

In [ ]:
print(series.loc[0])

Bandu

In [125]:
print(series.iloc[0])

Bandu

## **Dataframe**

2D Representation

In [130]:
data = {
    "name": ["Ram", "Sita", "Hari"],
    "marks": [80, 90, 70]
}

df = pd.DataFrame(data)
print(df, type(df), sep='\n')

   name  marks
0   Ram     80
1  Sita     90
2  Hari     70
<class 'pandas.core.frame.DataFrame'>

In [132]:
import pandas as pd
import numpy as np

data = [['Bandu', 'USA'], ['Baklol', 'India'], ['Baka', 'Japan']]
df = pd.DataFrame(data, columns=['name', 'country'])
print(df)

     name country
0   Bandu     USA
1  Baklol   India
2    Baka   Japan

In [137]:
# print(df[0])
# print(df[0][0])
print(df['country'][0])

USA

In [67]:
print(df.head(1))

    name country
0  Bandu     USA

In [69]:
print(df.tail(1))

   name country
2  Baka   Japan

### **More Attributes**

In [79]:
print(df.shape, df.columns, df.dtypes, sep='\n\n')

(3, 2)

Index(['name', 'country'], dtype='object')

name       object
country    object
dtype: object

In [138]:
print(df.info)
print()
print(df.info())

<bound method DataFrame.info of      name country
0   Bandu     USA
1  Baklol   India
2    Baka   Japan>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      object
 1   country  3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes
None

### **Indexing & Subsetting**

In [40]:
import pandas as pd

data = {
    'country': ['Nepal', 'Nepal', 'India', 'USA', 'China'],
    'chars': [5, 5, 5, 3, 5],
    'initial': ['N', 'N', 'I', 'U', 'C']
}

df = pd.DataFrame(data)

print(df)

  country  chars initial
0   Nepal      5       N
1   Nepal      5       N
2   India      5       I
3     USA      3       U
4   China      5       C

In [42]:
print(df['country'][3])

USA

In [44]:
# Subsetting
print(df[['initial', 'chars']])

  initial  chars
0       N      5
1       N      5
2       I      5
3       U      3
4       C      5

### **Slicing: loc vs iloc**

loc: Label

iloc: Index

In [45]:
import pandas as pd

df = pd.DataFrame({'id': [1, 2, 3], 'names': ['Antu', 'Bandu', 'Chandu']}, index=[-1, 0, 1])

print(df)
print("\n")

print(df.loc[0])
print("\n")

print(df.iloc[0])

    id   names
-1   1    Antu
 0   2   Bandu
 1   3  Chandu


id           2
names    Bandu
Name: 0, dtype: object


id          1
names    Antu
Name: -1, dtype: object

In [46]:
print(df.loc[0:3])

   id   names
0   2   Bandu
1   3  Chandu

In [26]:
print(df.iloc[0:3])

    id   names
-1   1    Antu
 0   2   Bandu
 1   3  Chandu

### **Filtering**

In [49]:
import numpy as np
import pandas as pd

arr = np.array(range(1, 11))
df = pd.DataFrame(arr, columns=['nums'])
print(df)

   nums
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10

In [54]:
evenDf = df[df['nums']%2 == 0]
print(evenDf)

   nums
1     2
3     4
5     6
7     8
9    10

### **Merging & Joining Dataframes**

**Merge:** Merges dataframe using a common column.

**Join:** Joins different dataframe independent of the columns.

In [59]:
import pandas as pd

df1 = pd.DataFrame([['A', 20], ['B', 30], ['C', 40]], columns=['name', 'marks'])
df2 = pd.DataFrame({'name': ['A', 'B', 'D'], 'grade': ['A+', 'B+', 'F']})

print(df1, df2, sep='\n')

dfc = df1.merge(df2)
print(dfc)

  name  marks
0    A     20
1    B     30
2    C     40
  name grade
0    A    A+
1    B    B+
2    D     F
  name  marks grade
0    A     20    A+
1    B     30    B+

In [60]:
import pandas as pd

df1 = pd.DataFrame({'country': ['Nepal', 'India', 'USA'], 'currency': ['Rupees', 'Rupees', 'Dollar']})
print(df1)

print()

df2 = pd.DataFrame({'country': ['Nepal', 'USA'], 'continent': ['Asia', 'N. America']})
print(df2)

print()

df3 = pd.merge(df1, df2, on='country')
print(df3)

  country currency
0   Nepal   Rupees
1   India   Rupees
2     USA   Dollar

  country   continent
0   Nepal        Asia
1     USA  N. America

  country currency   continent
0   Nepal   Rupees        Asia
1     USA   Dollar  N. America

In [62]:
import pandas as pd

df1 = pd.DataFrame([[1, 10],[2, 20], [3, 30], [4, 40], [5, 50]], columns=['x', 'y'])
print(df1)

print()

df2 = pd.DataFrame([[11], [22], [33], [44], [55]], columns=['z'])
print(df2)

print()

df3 = df1.join(df2)
print(df3)

   x   y
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

    z
0  11
1  22
2  33
3  44
4  55

   x   y   z
0  1  10  11
1  2  20  22
2  3  30  33
3  4  40  44
4  5  50  55

**More @ [Geeks for Geeks](https://www.geeksforgeeks.org/pandas/python-pandas-merging-joining-and-concatenating/)**

## **Empty Values**

<img src='https://i1.sndcdn.com/artworks-000138605998-hvu0we-t500x500.jpg' height='300'>

In [68]:
import pandas as pd

data = {
    'name': ['Ram', 'Hari', 'Gita', ''],
    'marks': [20, None, 3, '']
}

df = pd.DataFrame(data)

print(df)
print()

mv = df.isnull()
print(mv)
print()

mv = df.isna()
print(mv)
print()

mv = df.notna()
print(mv)
print()

mv = df.notnull()
print(mv)
print()

   name marks
0   Ram    20
1  Hari  None
2  Gita     3
3

    name  marks
0  False  False
1  False   True
2  False  False
3  False  False

    name  marks
0  False  False
1  False   True
2  False  False
3  False  False

   name  marks
0  True   True
1  True  False
2  True   True
3  True   True

   name  marks
0  True   True
1  True  False
2  True   True
3  True   True

In [74]:
import pandas as pd
import numpy as np

d = {   
        'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, None],
        'Third Score': ['', 40, 80, 98]
    }
df = pd.DataFrame(d)
print(df)

df.fillna('Abs')

   First Score  Second Score Third Score
0        100.0          30.0
1         90.0          45.0          40
2          NaN          56.0          80
3         95.0           NaN          98

  First Score Second Score Third Score
0       100.0         30.0
1        90.0         45.0          40
2         Abs         56.0          80
3        95.0          Abs          98

In [76]:
import pandas as pd
import numpy as np

d = {   
        'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, None],
        'Third Score': [None, 40, 80, 98]
    }

print(df)

df = pd.DataFrame(d)

df.ffill()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [78]:
import pandas as pd
import numpy as np

d = {   
        'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, None],
        'Third Score': [None, 40, 80, 98]
    }

print(df)

df = pd.DataFrame(d)

df.bfill()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

**More @ [Geeks for Geeks](https://www.geeksforgeeks.org/data-analysis/working-with-missing-data-in-pandas/)**